### ISSUE TITLE
[Question] What about moving my rust API wrapper under the umbrella of this org?

### ISSUE THREAD

**Issue by eriol** [OpenSourceOrg/api#10]
Hello,
I wrote an API wrapper in rust: https://github.com/eriol/rust-opensource

I would be happy to maintain it under the umbrella of this organization.

My future plan are to support rust stable, so I will continue to work on it.

Thanks for considering this.

**Comment by paultag** [comment]
**love it**!! I'll do this tonight! Yay, thank you!!!

**Comment by eriol** [comment]
Yeah! :smile: 
No need to hurry! It's evening in Italy. I tried to transfer the repository, but it seems I need to be part of the organization first.

**Comment by paultag** [comment]
@eriol made the repo, and set you as an admin on it! https://github.com/OpenSourceOrg/rust-opensource

THANKS SO MUCH! :D

**Comment by eriol** [comment]
:tada: :tada: :tada: 
Many thanks! :smile:
