### ISSUE TITLE
[QUESTION] Made a nodejs wrapper for api.opensource.org

### ISSUE THREAD

**Issue by alex-jose** [OpenSourceOrg/api#11]
Hi
I just made a nodejs wrapper for the API at https://github.com/alex-jose/node-opensource and published it on npm.

What do you think about moving the project under this organization?

Thanks.

**Comment by paultag** [comment]
@alex-jose: I love the idea! Thank you! This is great! Let me make a repo and add you to it now!

Thank you so much! Let's get a PR against the doc markdown after it's all set :D

**Comment by paultag** [comment]
@alex-jose you're an admin of that repo! Closing this issue for now!

**Comment by alex-jose** [comment]
Thanks :) :)
