### ISSUE TITLE
Elisp wrapper

### ISSUE THREAD

**Issue by nlamirault** [OpenSourceOrg/api#12]
Hello,
I wrote an API wrapper in elisp : https://github.com/nlamirault/opensource.el

Documentation of API is available on this branch `develop`.

**Comment by paultag** [comment]
@nlamirault Love it! Thank you so much! Was writing one, but I was having a hard time with https - this is great!

Do you want to move it under `OpenSourceOrg`? I can make a new repo and give you admin bits on it!

**Comment by nlamirault** [comment]
Sure !

**Comment by paultag** [comment]
Done! Thank you  :D

**Comment by nlamirault** [comment]
https://github.com/melpa/melpa/pull/4277
