### ISSUE TITLE
Perl wrapper

### ISSUE THREAD

**Issue by pablrod** [OpenSourceOrg/api#13]
Hello

I wrote an API wrapper in Perl: https://github.com/pablrod/p5-OpenSourceOrg-API and I've published it on CPAN: https://metacpan.org/pod/OpenSourceOrg::API

**Comment by paultag** [comment]
Oh! Awesome, thank you @pablrod! Would you like to move that repo under OpenSourceOrg?

**Comment by pablrod** [comment]
Sure! It would be great!!

**Comment by paultag** [comment]
@pablrod sorry for the lag - I've created the repo and set you as an admin on it!

**Comment by pablrod** [comment]
Thank you! And don't worry for the lag
