### ISSUE TITLE
PHP wrapper

### ISSUE THREAD

**Issue by ghost** [OpenSourceOrg/api#14]
Hi,

I've just written a PHP wrapper for the API: https://github.com/Arcesilas/php-opensource

I it worth integrating to the list of available wrapper?

**Comment by webmink** [comment]
@paultag @zacchiro What do you think? (I'm tidying so apologies for waking the old issue!)

**Comment by zacchiro** [comment]
Repo of the wrapper seems to no longer exist. I'm closing this for the time being. Happy to reconsider if the wrapper reappears.
