### ISSUE TITLE
Renew SSL certificate

### ISSUE THREAD

**Issue by eriol** [OpenSourceOrg/api#15]
Hello,
sorry if this is the wrong way to report the issue.

SSL certificate of [api.opensource.org](https://api.opensource.org) expired at the end of the last monday:
```
openssl s_client -status -connect api.opensource.org:443 2>&1 | awk '/^depth=0 OU/ {getline; print $0}'
```
will give:
```
verify error:num=10:certificate has expired
notAfter=Jun 11 23:59:59 2018 GMT
```

Could it be renewed? letsencrypt could be an option instead of Gandi, also in term of automatic renewal.

Thanks!

**Comment by massonpj** [comment]
Thanks. We'll update this ASAP. We recently migrated to a new service and looks like we missed one.
Patrick

**Comment by eriol** [comment]
@massonpj thanks for the quick reply, no need to hurry. I noticed the problem recompiling one example of [OpenSourceOrg/rust-opensource](https://github.com/OpenSourceOrg/rust-opensource): currently it's not possible to ignore certificate validation because the feature is not supported yet by the library I'm using but anyway I'm not sure to want that feature exposed in rust-opensource.

**Comment by Ironholds** [comment]
A brief note that while it is not urgent for commenters above, I'm getting some notes from the system administrators at CRAN (I maintain the R binding) to get the unit test failures caused by this expiry fixed posthaste :(. So (recognising it's the weekend and people are busy!) a sort of broad ETA I could send back to them at least would be most gratefully received!

**Comment by eriol** [comment]
@massonpj any update on this? If I can help in some way, let me know!

**Comment by massonpj** [comment]
Eeech, I thought this was resolved when we updated our other certs. Let me check.

**Comment by massonpj** [comment]
@eriol Should be good. Let me know if there is an issue.

**Comment by nickvidal** [comment]
We moved api.opensource.org to the same server as opensource.org and they are now using the same SSL certificate (from Let's Encrypt).

**Comment by eriol** [comment]
@massonpj @nickvidal many thanks!
