### ISSUE TITLE
API endpoint not reachable

### ISSUE THREAD

**Issue by orviz** [OpenSourceOrg/api#19]
Cannot access API endpoint at https://api.opensource.org/

**Comment by webmink** [comment]
Thanks for reporting. We have had some infrastructure changes recently and the experimental API service has unfortunately gone down as a consequence. At present it is run by volunteers, but we hope soon to have it become a formal part of OSI's infrastructure with a SLA.

I'd appreciate understanding your use case. Would you be willing to share please? Send to webmink@opensource.org

**Comment by orviz** [comment]
Thanks for the feedback, let's hope it can get back to normal operation soon. Just shared with you our use case.

**Comment by webmink** [comment]
OK, I am now seeing all the endpoints in https://github.com/OpenSourceOrg/api/blob/master/doc/endpoints.md working fine.
